# Generated by Django 4.2.9 on 2024-01-07 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_category_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
